name: Compile Binder Module

on:
  push:
    paths:
      - 'drivers/android/**'
      - '.github/workflows/compile-binder.yml'
  pull_request:
    paths:
      - 'drivers/android/**'
  workflow_dispatch:  # 允许手动触发

jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kernel_version: ['6.12']  # 可以添加多个版本

    steps:
      - name: Checkout kernel source
        uses: actions/checkout@v4
        with:
          ref: v${{ matrix.kernel_version }}
          fetch-depth: 1

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev \
            libssl-dev flex bison libelf-dev dwarves zstd

      - name: Prepare kernel configuration
        run: |
          # 使用默认配置
          make defconfig
          
          # 启用 binder 相关配置
          scripts/config --enable CONFIG_ANDROID
          scripts/config --enable CONFIG_ANDROID_BINDER_IPC
          scripts/config --enable CONFIG_ANDROID_BINDERFS
          scripts/config --enable CONFIG_ANDROID_BINDER_IPC_SELFTEST

      - name: Build kernel modules
        run: |
          # 编译 binder 相关模块
          make M=drivers/android -j$(nproc)

      - name: Verify build output
        run: |
          # 检查编译结果
          ls -l drivers/android/*.ko
          
          # 输出模块信息
          for ko in drivers/android/*.ko; do
            modinfo $ko
          done

      - name: Upload binder modules
        uses: actions/upload-artifact@v4
        with:
          name: binder-modules-${{ matrix.kernel_version }}
          path: |
            drivers/android/*.ko
          retention-days: 7
