name: Compile Binder Module (Fix Symvers)
on:
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Linux 6.12
        uses: actions/checkout@v4
        with:
          repository: torvalds/linux
          ref: v6.12
          fetch-depth: 1

      - name: Install Dependencies
        run: |
          sudo apt update && sudo apt install -y \
            build-essential libncurses5-dev libssl-dev \
            flex bison libelf-dev dwarves zstd bc \
            gcc-multilib libc6-dev-i386

      - name: Configure Kernel
        run: |
          make defconfig
          
          # 核心配置
          scripts/config --enable CONFIG_MODULES
          scripts/config --set-val CONFIG_ANDROID_BINDER_IPC m
          scripts/config --set-val CONFIG_ANDROID_BINDERFS m
          scripts/config --enable CONFIG_ANDROID
          scripts/config --disable CONFIG_MODULE_SIG
          
          # 验证配置
          cat .config | grep -E "CONFIG_MODULES|CONFIG_ANDROID_BINDER"

      - name: Build Kernel (Generate Symvers)
        run: |
          # 先编译内核核心部分生成必要的符号表
          make -j$(nproc) modules_prepare
          # 编译部分核心模块以生成Module.symvers
          make -j$(nproc) fs/
          make -j$(nproc) kernel/
          # 确认符号表文件生成
          ls -la Module.symvers

      - name: Copy Symvers to Android Directory
        run: |
          # 将主目录的符号表复制到驱动目录
          cp Module.symvers drivers/android/
          ls -la drivers/android/Module.symvers

      - name: Compile Binder Module
        run: |
          make M=drivers/android -j$(nproc) V=1

      - name: Check Results
        run: |
          echo "Drivers directory contents:"
          ls -la drivers/android/
          
          echo "Looking for .ko files:"
          find drivers/android/ -name "*.ko"
          
          if [ -f "drivers/android/binder.ko" ]; then
            echo "Binder module built successfully!"
            modinfo drivers/android/binder.ko
          else
            echo "Binder module not found!"
            exit 1
          fi

      - name: Upload Modules
        uses: actions/upload-artifact@v4
        with:
          name: binder-modules
          path: drivers/android/*.ko
