name: Build Binder Driver

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kernel source
        uses: actions/checkout@v4
        with:
          repository: torvalds/linux
          path: linux
      
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libncurses5-dev libssl-dev libelf-dev bison flex
      
      - name: Configure kernel
        run: |
          cd linux
          make defconfig
          echo "CONFIG_ANDROID=y" >> .config
          echo "CONFIG_ANDROID_BINDER_IPC=y" >> .config
          echo "CONFIG_ANDROID_BINDERFS=y" >> .config
      
      - name: Build binder modules
        run: |
          cd linux
          make modules -j$(nproc)
      
      - name: Upload built modules
        uses: actions/upload-artifact@v4
        with:
          name: binder-modules
          path: |
            linux/drivers/android/binder.ko
            linux/drivers/android/binderfs.ko
