name: Build Binder Driver
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-22.04  # 使用更稳定的Ubuntu版本
    steps:
      - name: System info
        run: |
          uname -a
          lsb_release -a
      
      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install -y \
            build-essential \
            gcc \
            make \
            libncurses5-dev \
            flex \
            bison \
            openssl \
            libssl-dev \
            libelf-dev \
            bc \
            git \
            libzstd-dev
      
      - name: Clone kernel source
        run: |
          git clone --depth 1 --branch v6.12 https://github.com/torvalds/linux.git
          cd linux
          ls -l drivers/android/
      
      - name: Configure kernel
        run: |
          cd linux
          # 生成默认配置
          make defconfig
          
          # 添加所有必要的Binder配置
          echo "CONFIG_ANDROID_BINDER_IPC=m" >> .config
          echo "CONFIG_ANDROID_BINDERFS=y" >> .config
          echo "CONFIG_ANDROID_BINDER_DEVICES=\"binder,hwbinder,vndbinder\"" >> .config  # 新增这一行
          echo "CONFIG_PROC_FS=y" >> .config
          echo "CONFIG_SYSFS=y" >> .config
          echo "CONFIG_MMU=y" >> .config
          
          # 验证所有配置项
          grep -E "CONFIG_ANDROID_BINDER|CONFIG_PROC_FS|CONFIG_SYSFS|CONFIG_MMU" .config
          
          # 准备模块编译环境
          make modules_prepare V=1
      
      - name: Build driver
        run: |
          cd linux
          # 编译Binder驱动
          make drivers/android/binder.ko V=1 -j$(nproc)
      
      - name: Check build result
        run: |
          if [ -f "linux/drivers/android/binder.ko" ]; then
            echo "Build successful"
            ls -l linux/drivers/android/binder.ko
            modinfo linux/drivers/android/binder.ko || true
          else
            echo "Build failed - binder.ko not found"
            exit 1
          fi
      
      - name: Upload artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: binder-module
          path: linux/drivers/android/binder.ko
          retention-days: 7
    
