name: Build Binder Driver
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update -y
          # 安装更完整的编译依赖
          sudo apt install -y \
            build-essential \
            gcc \
            g++ \
            make \
            libncurses5-dev \
            libncursesw5-dev \
            flex \
            bison \
            openssl \
            libssl-dev \
            libelf-dev \
            elfutils \
            bc \
            git \
            gcc-multilib \
            libc6-dev \
            pkg-config
          # 检查关键工具版本
          gcc --version
          make --version
      
      - name: Clone kernel source
        run: |
          git clone --depth 1 --branch v6.12 https://github.com/torvalds/linux.git
          cd linux
          # 显示当前分支信息
          git branch
      
      - name: Configure kernel
        run: |
          cd linux
          # 生成默认配置
          make defconfig
          # 确保配置工具可用
          if [ ! -f "scripts/config" ]; then
            echo "Error: scripts/config not found"
            exit 1
          fi
          # 配置 Binder 驱动为模块
          scripts/config --enable CONFIG_ANDROID_BINDER_IPC
          scripts/config --set-val CONFIG_ANDROID_BINDER_IPC m
          scripts/config --enable CONFIG_ANDROID_BINDERFS
          # 准备模块编译环境
          make modules_prepare
          # 检查配置是否生效
          grep CONFIG_ANDROID_BINDER_IPC .config
      
      - name: Build driver
        run: |
          cd linux
          # 编译时显示详细输出，便于调试
          make V=1 drivers/android/binder.ko -j$(nproc)
      
      - name: Check build result
        run: |
          if [ -f "linux/drivers/android/binder.ko" ]; then
            echo "Build successful"
            ls -l linux/drivers/android/binder.ko
          else
            echo "Build failed - binder.ko not found"
            exit 1
          fi
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: binder-module
          path: linux/drivers/android/binder.ko
          retention-days: 7
    
