name: Build Binder Driver
on: [workflow_dispatch]  # 允许手动触发
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libncurses5-dev flex bison openssl libssl-dev libelf-dev bc git
      
      - name: Clone kernel source
        run: |
          git clone --depth 1 --branch v6.12 https://github.com/torvalds/linux.git
          cd linux
      
      - name: Configure kernel
        run: |
          cd linux
          make defconfig
          scripts/config --enable CONFIG_ANDROID_BINDER_IPC
          scripts/config --set-val CONFIG_ANDROID_BINDER_IPC m
          make modules_prepare
      
      - name: Build driver
        run: |
          cd linux
          make drivers/android/binder.ko -j$(nproc)
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4  # 使用最新的 v4 版本
        with:
          name: binder-module
          path: linux/drivers/android/binder.ko
          retention-days: 7  # 可选：设置 artifact 保留天数
